version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: Dammy@123
      MYSQL_DATABASE: workdirk
    ports:
      - "3307:3306"
    networks:
      - workdirk-net
    # Ensures MySQL fully initializes before Go tries to connect
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pDammy@123"]
      interval: 5s
      timeout: 5s
      retries: 5

  workdirk-app:
    build: .
    container_name: workdirk-app
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=root:Dammy@123@tcp(mysql-db:3306)/workdirk?parseTime=true
    networks:
      - workdirk-net
    depends_on:
      mysql-db:
        condition: service_healthy

networks:
  workdirk-net:
    driver: bridge