version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=:8080
      # Notice 'db' is used here instead of 127.0.0.1
      - DATABASE_URL=root:secretpassword@tcp(db:3306)/workdirk?parseTime=true
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secretpassword
      MYSQL_DATABASE: workdirk
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pDammy@123"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: